int sizeOfArray(int size);
void keyboardInputArray(int *arr, int size);
void outputArray(int *arr, int size);
void outputTwoArray(int **arr, int line, int coll);
int amountNum(int *arr, int size, int amount);
int** memoryTwo(int **arr, int line, int coll);
int** inputNewArray(int *arr, int **narr, int size);
void buble(int **narr, int amount);
double timeBuble(int **narr, int amount, double time);
double timeShell(int *narr, int amount, double time);
void shell(int *arr, int size);
int* memory(int *arr, int size);
void randomInputArray(int *arr, int size);
int pInputArray(int operation);
int* inputArray(int *arr, int size, int operation);
void cleaning(int *arr);
int* changeArray(int *arr, int **narr, int *farr, int coll, int amount);
int* inputNewArrayB(int *arr, int *narrB, int size);
int** reBuble(int **narr, int amount);
void cleaningTwo(int **arr, int line);
int** timeReBuble(int **narr, int amount);
void outputTime(double time);
