void secondAssignment (void);
char* memorySecond (char *arr, int memorySt);
char* reallocationSecond(char *arr, int memorySt);
void printInputStringSecond(void);
void printInputSubstring(void);
char* inputStringSecond (char *arr, int memorySt);
char* inputSubstring (char *arr, int memorySt);
int searchNumOfElementsArray (char* arr);
int searchNumOfElementsSub (char* arr, int numOfElementsSub);
char* changMainString (char *arr, char *sarr, int numOfElementsSub, int numOfElements);
void outputStringSecond (char *arr);
void cleaningSecond(char* arr);
char* finalReallocationSecond (char *arr, int numOfElements);
